version: '3.9'

services:
  app:
    image: ghost:alpine
    container_name: blog-app
    restart: always
    ports:
      - '8081:2368'
    environment:
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=root
      - database__connection__password=!secret      # TODO: change this password
      - database__connection__database=blog-ghost
      - url=http://blog.my-domain                   # TODO: change this url
    volumes:
      - app:/var/lib/ghost/content
    depends_on:
      - db
  db:
    image: mysql:8.3
    container_name: blog-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=!secret                 # TODO: change this password
    volumes:
      - db:/var/lib/mysql
volumes:
  app:
  db: